// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envelope.proto

package com.chargeserver.ocpp;

public final class Envelope {
  private Envelope() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnvOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 timeout = 1;
    boolean hasTimeout();
    int getTimeout();
    
    // optional bool ping = 2;
    boolean hasPing();
    boolean getPing();
    
    // repeated .Env.Msg message = 3;
    java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg> 
        getMessageList();
    com.chargeserver.ocpp.Envelope.Env.Msg getMessage(int index);
    int getMessageCount();
    java.util.List<? extends com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder> 
        getMessageOrBuilderList();
    com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder getMessageOrBuilder(
        int index);
  }
  public static final class Env extends
      com.google.protobuf.GeneratedMessage
      implements EnvOrBuilder {
    // Use Env.newBuilder() to construct.
    private Env(Builder builder) {
      super(builder);
    }
    private Env(boolean noInit) {}
    
    private static final Env defaultInstance;
    public static Env getDefaultInstance() {
      return defaultInstance;
    }
    
    public Env getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chargeserver.ocpp.Envelope.internal_static_Env_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chargeserver.ocpp.Envelope.internal_static_Env_fieldAccessorTable;
    }
    
    public interface MsgOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required uint32 service = 1;
      boolean hasService();
      int getService();
      
      // optional bytes contents = 2;
      boolean hasContents();
      com.google.protobuf.ByteString getContents();
    }
    public static final class Msg extends
        com.google.protobuf.GeneratedMessage
        implements MsgOrBuilder {
      // Use Msg.newBuilder() to construct.
      private Msg(Builder builder) {
        super(builder);
      }
      private Msg(boolean noInit) {}
      
      private static final Msg defaultInstance;
      public static Msg getDefaultInstance() {
        return defaultInstance;
      }
      
      public Msg getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chargeserver.ocpp.Envelope.internal_static_Env_Msg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chargeserver.ocpp.Envelope.internal_static_Env_Msg_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required uint32 service = 1;
      public static final int SERVICE_FIELD_NUMBER = 1;
      private int service_;
      public boolean hasService() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getService() {
        return service_;
      }
      
      // optional bytes contents = 2;
      public static final int CONTENTS_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString contents_;
      public boolean hasContents() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      
      private void initFields() {
        service_ = 0;
        contents_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasService()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, service_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, contents_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, service_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, contents_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.chargeserver.ocpp.Envelope.Env.Msg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.chargeserver.ocpp.Envelope.Env.Msg prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.chargeserver.ocpp.Envelope.internal_static_Env_Msg_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.chargeserver.ocpp.Envelope.internal_static_Env_Msg_fieldAccessorTable;
        }
        
        // Construct using com.chargeserver.ocpp.Envelope.Env.Msg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          service_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          contents_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.chargeserver.ocpp.Envelope.Env.Msg.getDescriptor();
        }
        
        public com.chargeserver.ocpp.Envelope.Env.Msg getDefaultInstanceForType() {
          return com.chargeserver.ocpp.Envelope.Env.Msg.getDefaultInstance();
        }
        
        public com.chargeserver.ocpp.Envelope.Env.Msg build() {
          com.chargeserver.ocpp.Envelope.Env.Msg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.chargeserver.ocpp.Envelope.Env.Msg buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.chargeserver.ocpp.Envelope.Env.Msg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.chargeserver.ocpp.Envelope.Env.Msg buildPartial() {
          com.chargeserver.ocpp.Envelope.Env.Msg result = new com.chargeserver.ocpp.Envelope.Env.Msg(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.service_ = service_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.contents_ = contents_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.chargeserver.ocpp.Envelope.Env.Msg) {
            return mergeFrom((com.chargeserver.ocpp.Envelope.Env.Msg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.chargeserver.ocpp.Envelope.Env.Msg other) {
          if (other == com.chargeserver.ocpp.Envelope.Env.Msg.getDefaultInstance()) return this;
          if (other.hasService()) {
            setService(other.getService());
          }
          if (other.hasContents()) {
            setContents(other.getContents());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasService()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                service_ = input.readUInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                contents_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required uint32 service = 1;
        private int service_ ;
        public boolean hasService() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getService() {
          return service_;
        }
        public Builder setService(int value) {
          bitField0_ |= 0x00000001;
          service_ = value;
          onChanged();
          return this;
        }
        public Builder clearService() {
          bitField0_ = (bitField0_ & ~0x00000001);
          service_ = 0;
          onChanged();
          return this;
        }
        
        // optional bytes contents = 2;
        private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasContents() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public com.google.protobuf.ByteString getContents() {
          return contents_;
        }
        public Builder setContents(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          contents_ = value;
          onChanged();
          return this;
        }
        public Builder clearContents() {
          bitField0_ = (bitField0_ & ~0x00000002);
          contents_ = getDefaultInstance().getContents();
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:Env.Msg)
      }
      
      static {
        defaultInstance = new Msg(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Env.Msg)
    }
    
    private int bitField0_;
    // optional uint32 timeout = 1;
    public static final int TIMEOUT_FIELD_NUMBER = 1;
    private int timeout_;
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTimeout() {
      return timeout_;
    }
    
    // optional bool ping = 2;
    public static final int PING_FIELD_NUMBER = 2;
    private boolean ping_;
    public boolean hasPing() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getPing() {
      return ping_;
    }
    
    // repeated .Env.Msg message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg> message_;
    public java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg> getMessageList() {
      return message_;
    }
    public java.util.List<? extends com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    public int getMessageCount() {
      return message_.size();
    }
    public com.chargeserver.ocpp.Envelope.Env.Msg getMessage(int index) {
      return message_.get(index);
    }
    public com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }
    
    private void initFields() {
      timeout_ = 0;
      ping_ = false;
      message_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMessageCount(); i++) {
        if (!getMessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, timeout_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, ping_);
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(3, message_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timeout_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, ping_);
      }
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, message_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.chargeserver.ocpp.Envelope.Env parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chargeserver.ocpp.Envelope.Env parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chargeserver.ocpp.Envelope.Env prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.chargeserver.ocpp.Envelope.EnvOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chargeserver.ocpp.Envelope.internal_static_Env_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chargeserver.ocpp.Envelope.internal_static_Env_fieldAccessorTable;
      }
      
      // Construct using com.chargeserver.ocpp.Envelope.Env.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timeout_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ping_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chargeserver.ocpp.Envelope.Env.getDescriptor();
      }
      
      public com.chargeserver.ocpp.Envelope.Env getDefaultInstanceForType() {
        return com.chargeserver.ocpp.Envelope.Env.getDefaultInstance();
      }
      
      public com.chargeserver.ocpp.Envelope.Env build() {
        com.chargeserver.ocpp.Envelope.Env result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.chargeserver.ocpp.Envelope.Env buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.chargeserver.ocpp.Envelope.Env result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.chargeserver.ocpp.Envelope.Env buildPartial() {
        com.chargeserver.ocpp.Envelope.Env result = new com.chargeserver.ocpp.Envelope.Env(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeout_ = timeout_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ping_ = ping_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chargeserver.ocpp.Envelope.Env) {
          return mergeFrom((com.chargeserver.ocpp.Envelope.Env)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.chargeserver.ocpp.Envelope.Env other) {
        if (other == com.chargeserver.ocpp.Envelope.Env.getDefaultInstance()) return this;
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        if (other.hasPing()) {
          setPing(other.getPing());
        }
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000004);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMessageCount(); i++) {
          if (!getMessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeout_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ping_ = input.readBool();
              break;
            }
            case 26: {
              com.chargeserver.ocpp.Envelope.Env.Msg.Builder subBuilder = com.chargeserver.ocpp.Envelope.Env.Msg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 timeout = 1;
      private int timeout_ ;
      public boolean hasTimeout() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTimeout() {
        return timeout_;
      }
      public Builder setTimeout(int value) {
        bitField0_ |= 0x00000001;
        timeout_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeout_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool ping = 2;
      private boolean ping_ ;
      public boolean hasPing() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getPing() {
        return ping_;
      }
      public Builder setPing(boolean value) {
        bitField0_ |= 0x00000002;
        ping_ = value;
        onChanged();
        return this;
      }
      public Builder clearPing() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ping_ = false;
        onChanged();
        return this;
      }
      
      // repeated .Env.Msg message = 3;
      private java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          message_ = new java.util.ArrayList<com.chargeserver.ocpp.Envelope.Env.Msg>(message_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chargeserver.ocpp.Envelope.Env.Msg, com.chargeserver.ocpp.Envelope.Env.Msg.Builder, com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder> messageBuilder_;
      
      public java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      public com.chargeserver.ocpp.Envelope.Env.Msg getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      public Builder setMessage(
          int index, com.chargeserver.ocpp.Envelope.Env.Msg value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMessage(
          int index, com.chargeserver.ocpp.Envelope.Env.Msg.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMessage(com.chargeserver.ocpp.Envelope.Env.Msg value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMessage(
          int index, com.chargeserver.ocpp.Envelope.Env.Msg value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMessage(
          com.chargeserver.ocpp.Envelope.Env.Msg.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMessage(
          int index, com.chargeserver.ocpp.Envelope.Env.Msg.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMessage(
          java.lang.Iterable<? extends com.chargeserver.ocpp.Envelope.Env.Msg> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          super.addAll(values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      public com.chargeserver.ocpp.Envelope.Env.Msg.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      public com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      public com.chargeserver.ocpp.Envelope.Env.Msg.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            com.chargeserver.ocpp.Envelope.Env.Msg.getDefaultInstance());
      }
      public com.chargeserver.ocpp.Envelope.Env.Msg.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, com.chargeserver.ocpp.Envelope.Env.Msg.getDefaultInstance());
      }
      public java.util.List<com.chargeserver.ocpp.Envelope.Env.Msg.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chargeserver.ocpp.Envelope.Env.Msg, com.chargeserver.ocpp.Envelope.Env.Msg.Builder, com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.chargeserver.ocpp.Envelope.Env.Msg, com.chargeserver.ocpp.Envelope.Env.Msg.Builder, com.chargeserver.ocpp.Envelope.Env.MsgOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Env)
    }
    
    static {
      defaultInstance = new Env(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Env)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Env_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Env_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Env_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Env_Msg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016envelope.proto\"i\n\003Env\022\017\n\007timeout\030\001 \001(\r" +
      "\022\014\n\004ping\030\002 \001(\010\022\031\n\007message\030\003 \003(\0132\010.Env.Ms" +
      "g\032(\n\003Msg\022\017\n\007service\030\001 \002(\r\022\020\n\010contents\030\002 " +
      "\001(\014B!\n\025com.chargeserver.ocppB\010Envelope"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Env_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Env_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Env_descriptor,
              new java.lang.String[] { "Timeout", "Ping", "Message", },
              com.chargeserver.ocpp.Envelope.Env.class,
              com.chargeserver.ocpp.Envelope.Env.Builder.class);
          internal_static_Env_Msg_descriptor =
            internal_static_Env_descriptor.getNestedTypes().get(0);
          internal_static_Env_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Env_Msg_descriptor,
              new java.lang.String[] { "Service", "Contents", },
              com.chargeserver.ocpp.Envelope.Env.Msg.class,
              com.chargeserver.ocpp.Envelope.Env.Msg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
